### ISSUE TITLE
Not working for player without mojang cape

### ISSUE THREAD

**Issue by kakis69** [SuchBlue/of-capes#2]
#1 
I don't have a Mojang cape or an Optifine cape. Now I wanted to try out the code and added it to my mod and switched the server that provides the capes to one of mine. Now I can't give myself a cape, but other players who have a Mojang cape can.

**Comment by SuchBlue** [comment]
This issue is out of the scope of the project. This was intended to be a continuation of [dragonostic/of-capes](https://github.com/dragonostic/of-capes) and not really a template for a plugin that interfaces with capes.. and even then, I don't have access to your code so I can't help you with that either if I wanted to.
